# Generated by Django 5.0.3 on 2024-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100, verbose_name='Название')),
        ),
    ]
