# Generated by Django 4.2.7 on 2024-04-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_active_version',
            new_name='is_active',
        ),
    ]
