# Generated by Django 5.0.3 on 2024-04-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can publish product'), ('change_description', 'Can change description'), ('change_category', 'Can change categoty')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
